### ISSUE TITLE
pixelRatio

### ISSUE THREAD

**Issue by hampsterx** [nbrucker/widget_to_image#1]
hi there, nice lib. Can you make the `pixelRatio` as argument thanks. Default image quality seems pretty poor.

https://github.com/flutter/flutter/issues/21269

**Comment by hampsterx** [comment]
also looks like this line is duplicated..

```
		buildOwner.buildScope(rootElement);
```

**Comment by nbrucker** [comment]
Hi, thanks a lot!
I use the package in my app and the image quality is pretty good but that's a really good idea, I'm gonna make it an argument right away.

Also well seen for the duplicate :)

**Comment by nbrucker** [comment]
The 1.0.3 is out, thanks for the help !

**Comment by hampsterx** [comment]
```
	devicePixelRatio: 1.0,
```

thnx for speedy response but oops ya missed that hardcode :P

**Comment by nbrucker** [comment]
Haha I'm on it :p
Do you also want to be able to modify this `size: Size(double.maxFinite, double.maxFinite)` ?

**Comment by hampsterx** [comment]
might as well make them args, no harm but have not looked to see what the viewConfiguration size actually does

**Comment by nbrucker** [comment]
I added `alignment`, `size` and `devicePixelRatio` as arguments :)
Once again thanks a lot for the help @hampsterx !

**Comment by hampsterx** [comment]
just FYI for others doing screenshots with image content. use `FilterQuality.high` on your images to avoid pixelation, took me a while to figure this out :P
